### ISSUE TITLE
Invalid format error, when setting a value by Xpath containing a selector

### ISSUE THREAD

**Issue by tb1402** [iMicknl/python-sagemcom-api#183]
## Versions

| Key               | Value |
| ----------------- | ----- |
| Package version   |   1.0.8  (installed by pip)    |
| Python Version    |   3.10    |
| F@st Router Model |    Speedport Pro   |

## Describe the bug

When trying to set a value in a xpath which contains a selector e.g. ""Device/UserInterface/LocalLEDSignaling/LEDs/LED[Name='LED_WLAN']/Enabled"
the response is:
```
sagemcom_api.exceptions.BadRequestException: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <title>400 - Bad Request</title>
  </head>
  <body>
    <h1>400 - Bad Request</h1>
    <p>Invalid URL encoded format</p>
  </body>
</html>
```

## To Reproduce

1. Call set_value_by_xpath with a xpath that contains a selector  "some/xpath[Key='Value']" as shown in example above.
2. The above error gets raised

## Expected behavior

Set the value for the xpath without errors.

## Additional context

I noticed, that the get_value_by_xpath method uses "xpath": urllib.parse.quote(xpath), for each action, but the set_value method does not.
I fixed the problem by replacing "xpath": xpath, in the actions dict in set_value_by_xpath with "xpath": urllib.parse.quote(xpath), and it worked without any errors.

[bug]

**Comment by iMicknl** [comment]
Would you be willing to make a PR to fix this issue?

**Comment by nandito** [comment]
Weird, but I get errors if with this `"xpath": urllib.parse.quote(xpath)` solution now. Removing it and using `"xpath": xpath` works well.

I inspected the xpaths in the browser console when changing a value on the dashboard. The xpath was not escaped there either.

Request on the dashboard:
```json
{
    "request": {
        "id": 29,
        "session-id": 1962749877,
        "priority": false,
        "actions": [
            {
                "id": 0,
                "method": "setValue",
                "xpath": "Device/WiFi/Radios/Radio[Alias=\"RADIO2G4\"]/TransmitPower",
                "parameters": { "value": "60" }
            }
        ],
        "cnonce": 12345,
        "auth-key": "somekey"
    }
}
```

I grabbed the `xpath` from the response above and used it in the code:
```python
transmitPowerXPath = "Device/WiFi/Radios/Radio[Alias=\"RADIO2G4\"]/TransmitPower"
custom_command_output = await client.set_value_by_xpath(transmitPowerXPath, "60")
```
Here's the value of the `actions` in the `client.py`'s `set_value_by_xpath`:
```json
{
    "id": 0,
    "method": "setValue",
    "xpath": "Device/WiFi/Radios/Radio%5BAlias%3D%22RADIO2G4%22%5D/TransmitPower",
    "parameters": { "value": "60" },
    "options": {}
}
```

This request has failed with an `'Invalid action parameter'` error.

If I don't use the `urllib.parse.quote()` on the `xpath` field, it works well. `actions`:
```json
{
    "id": 0,
    "method": "setValue",
    "xpath": "Device/WiFi/Radios/Radio[Alias=\"RADIO2G4\"]/TransmitPower",
    "parameters": { "value": "60" },
    "options": {}
}
```
The response is `Applied` in this case.

I'm using the sample code from the README's [Getting Started](https://github.com/iMicknl/python-sagemcom-api?tab=readme-ov-file#getting-started) section.
