### ISSUE TITLE
I can't access to the xpath  Sagemcom f@st 5566

### ISSUE THREAD

**Issue by barnouch** [iMicknl/python-sagemcom-api#249]
## Versions

| Key               | Value |
| ----------------- | ----- |
| Package version   |       |
| Python Version    |    3.11   |
| F@st Router Model |    5566   |

## Describe the bug
I can't access to the xpath

Sagemcom f@st 5566
![358902939_498517329139114_3377358483880616649_n](https://github.com/iMicknl/python-sagemcom-api/assets/4481234/cb7d55fc-adad-499f-8489-279d4843f137)

Give a clear and concise description of what the bug is.

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by iMicknl** [comment]
The error tells you that this specific path does not exist.

**Comment by barnouch** [comment]
> The error tells you that this specific path does not exist.

So what's the solution please

**Comment by iMicknl** [comment]
What do you want to achieve?

Please note that I don't actively work on this Python client anymore, thus not sure how much I can support 😉.

**Comment by barnouch** [comment]
> What do you want to achieve?
> 
> Please note that I don't actively work on this Python client anymore, thus not sure how much I can support 😉.

I want to change some value (vlan for vdsl) to connect with bell HH3000 with another isp , that's it !

Thank you sir

**Comment by iMicknl** [comment]
@barnouch please know that you probably can't change something, that you can't change via the vendor interface.

The xpath feature can be used to get a specific path. You can try to use a `*` to get all paths. I can't support you in picking the right query, since you already have access it seems. You just need to pick the right xpath for your usecase.

**Comment by barnouch** [comment]
> @barnouch please know that you probably can't change something, that you can't change via the vendor interface.
> 
> The xpath feature can be used to get a specific path. You can try to use a `*` to get all paths. I can't support you in picking the right query, since you already have access it seems. You just need to pick the right xpath for your usecase.

so finally i get access to the router 
but my problem is : _using Bell HH3000 (SgemcomF@st 5566) with other ISP from other country_
my question is : how to find **VlanID** default value for **VDSL2** (i think it is 35) and change it ? this value is listed in python code ? thank you
