### ISSUE TITLE
Unsupported F@st model: FAST5689E (Bell Canada Giga Hub)

### ISSUE THREAD

**Issue by Bungeetaco** [iMicknl/python-sagemcom-api#250]
## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               |   FAST 5689E    |
| Hardware Version         |    HH4000-E   |
| Software Version         |   3.2.4.0-75-gd888e9    |

## Describe the bug

Running the sample script manages to login to the router, and fetch MAC address information as well as device names, but fails with a traceback during the step after with a XMO_UNKNOWN_PATH_ERR error code

## To Reproduce

1. Change encryption method in sample script to SHA512. Add credentials
2. Run script
3. Issue occurs

## Expected behavior

Get all values from router

## Screenshots

![image](https://github.com/iMicknl/python-sagemcom-api/assets/5958682/d576e5d3-5b79-4b43-a743-a6af8f14d64d)

## Additional context

```
python3 ./sagemcom.py
0C:AC:8A:05:02:BE 5690
_Redacted additional MAC addresses and device names_
Traceback (most recent call last):
  File "/home/bungee/./sagemcom.py", line 37, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/bungee/./sagemcom.py", line 30, in main
    custom_command_output = await client.get_value_by_xpath("Device/UserInterface/AdvancedMode")
  File "/home/bungee/.local/lib/python3.10/site-packages/sagemcom_api/client.py", line 311, in get_value_by_xpath
    response = await self.__api_request_async([actions], False)
  File "/home/bungee/.local/lib/python3.10/site-packages/sagemcom_api/client.py", line 235, in __api_request_async
    raise UnknownPathException(action_error)
sagemcom_api.exceptions.UnknownPathException: {'code': 16777242, 'description': 'XMO_UNKNOWN_PATH_ERR'}
```

[bug]

**Comment by iMicknl** [comment]
XMO_UNKNOWN_PATH_ERR means that this specific path is not supported on your hardware.
