### ISSUE TITLE
Advanced XPATH paths don't work - need to encode the xpath value

### ISSUE THREAD

**Issue by DCAG** [iMicknl/python-sagemcom-api#29]
https://github.com/iMicknl/python-sagemcom-api/blob/58e6e52743623a6648f4bc2e4cd7c96da51210ed/sagemcom_api/client.py#L288

xpath path that will fail for example:
```xpath
Device/WiFi/AccessPoints/AccessPoint[@uid='2']/Enable
```

**Comment by simlaf** [comment]
I ran into that issue myself.  
I had to modify __api_request_async the following:

`from urllib.parse import quote
async with self.session.post(
            api_host, data="req=" + quote(json.dumps(payload, separators=(",", ":")).encode("utf-8"))
        )
`

**Comment by iMicknl** [comment]
@DCAG thanks for reporting! I haven't faced this myself yet, but it looks like it would be a good addition. Could you perhaps do a pull request?

@DCAG / @simlaf which model Sagemcom do you have? And for which purpose are you utilizing this library? I am looking for contributors to help on creating the Home Assistant integration. :-)

**Comment by simlaf** [comment]
I'm on Bell FIbe, so it's the 5566.  I just migrated to pfSense last weekend, so I probably won't make use of this library anymore.  I did add a few things though, you can have a look at my fork and use whatever you want.  Note though that I'm not a professional developper, so the code probably isn't up to par, but it worked for me :)

**Comment by DCAG** [comment]
I'm using Sagemcom f@st 5657.
I'm a PowerShell developer, but noob in Python. I migrated most of the code to PowerShell to make it easier for me to debug.
I'll see what I can do...

Anyway in my converted code I encoded the xpath just before creating the JSON object for the request

```powershell
$actions = @"
{
    "id": 0,
    "method": "getValue",
    "xpath": "$([System.Web.HttpUtility]::UrlEncode($xpath))",
    "options": $($options | ConvertTo-Json)
}
"@
```

**Comment by iMicknl** [comment]
Thanks both! I will have a look when I have time and implement some of these changes.

**Comment by iMicknl** [comment]
Thanks for reporting, I (hopefully) just fixed it! 1.0.3 includes this fix and has been published to PyPi.

@DCAG in case you have time, please have a look at my question above :).

**Comment by iMicknl** [comment]
@simlaf do you want to do a PR with your changes, or should I have a look at your fork and migrate it?

**Comment by DCAG** [comment]
@iMicknl I'm using the F@st 5657 (or Sagemcom Fast5657IL) it uses MD5.

**Comment by barnouch** [comment]
> I'm on Bell FIbe, so it's the 5566. I just migrated to pfSense last weekend, so I probably won't make use of this library anymore. I did add a few things though, you can have a look at my fork and use whatever you want. Note though that I'm not a professional developper, so the code probably isn't up to par, but it worked for me :)

Hello freind
Please help me to get access to the bell hh3000
The code show me an path error
