### ISSUE TITLE
Unable to connect due to GUI providing self-signed untrusted Certificate

### ISSUE THREAD

**Issue by bunnis** [iMicknl/python-sagemcom-api#298]
## Versions

| Key               | Value |
| ----------------- | ----- |
| Package version   |    1.1.0   |
| Python Version    |    Python 3.10.12   |
| F@st Router Model |   FAST 5688S (not in the supported list)    |

## Describe the bug
Unable to connect due to GUI providing self-signed untrusted Certificate. The error messages are different between python version but I'm able to connect if the certificate is trusted.
```
bunnis@bjb:~$ python3 --version
Python 3.10.12
bunnis@bjb:~$ python3 sunrise.py
Cannot connect to host 192.168.1.1:443 ssl:default [[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1007)]


bunnis@devops:~$ python --version
Python 3.8.10
bunnis@devops:~$ python sunrise.py
Cannot connect to host 192.168.1.1:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1131)')]
```

## To Reproduce

1. Copy the quickstart script. Fill out the necessary details
2. Ensure that the GUI page is using an untrusted cert (or use a proxy to emulate such)
3. Run it, observe error

## Expected behavior

It would be expected to have an option to ignore untrusted certificates. The GUI page comes with an untrusted self-signed cert by default and I don't have a way to change it. I used a MITM proxy to make the script work

## Additional context

[bug]

**Comment by iMicknl** [comment]
You can pass in a aiohttp session with SSL turned off, have you tried this? This is how ha-sagemcom-fast works as well.

**Comment by bunnis** [comment]
True you are right, I was hoping for an option to control this, but I guess an aiohttp makes more sense, otherwise you would probably need to add additional options too.  I'm marking this as closed.
