### ISSUE TITLE
Turn on/off Wifi

### ISSUE THREAD

**Issue by tik9** [iMicknl/python-sagemcom-api#300]
Is it possible to turn on/off the wifi 2.5 or 5 ghz  and get the current value if turned on or off?

[The fritzbox python api](https://fritzconnection.readthedocs.io/en/1.2.1/sources/introduction.html) has it all:

With the mentioned api, code is:
`FritzConnection(password=os.getenv('fb'), user='fritz').call_action('WLANConfiguration1', 'SetEnable', <true/false>`

'WLANConfiguration1' is Wifi 2.5 Ghz.

Trying `client.get_value_by_xpath("Device/UserInterface")` in your code, I did not find wifi in the output.

**Comment by iMicknl** [comment]
This is a hard one for me to debug without having access to the device. By any chance, can you execute this in the router webui? Via the browser, you can capture the XHR requests and see which actions are being executed via the Sagemcom API.

**Comment by iMicknl** [comment]
@tik9 please let me know if this is still relevant, and we can reopen.
