### ISSUE TITLE
F@st 5670 ServerDisconnectedError while get DeviceInfo

### ISSUE THREAD

**Issue by h00t2y** [iMicknl/python-sagemcom-api#340]
## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               |  F5670v2     |
| Hardware Version         |  3.0     |
| Software Version         |    v19.1.164.16.14.3   |

I use SHA512 hashing. Tried on 3 different debian with python 3.7.3 and 3.9.3 as well.

## Describe the bug

The python script fails with error : aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
It happens when the script runs Device/DeviceInfo command. 

I can see from the router's log that login was successfull.
Please find attached log of tree values.

What could be my problem?
[sagemcom5670valuestree.txt](https://github.com/user-attachments/files/16568663/sagemcom5670valuestree.txt)

[bug]

**Comment by h00t2y** [comment]
Made some changes according to #252
In client.py:
- connector=TCPConnector(ssl=verify_ssl),
+ - connector=TCPConnector(ssl=verify_ssl, force_close=True),

+     await asyncio.sleep(0.1)
        async with self.session.post(......

Now with this:
        device_info = await client.get_device_info()
        print(f"{device_info.id} {device_info.model_name}")
Output:
88:0F:A2:55:24:48 Fast5670AXv2

**Comment by iMicknl** [comment]
@h00t2y have you tried the latest version of the package? We can see if we can include these fixes to the package.

**Comment by h00t2y** [comment]
Oh. I was on 1.0.5. :) 1.3.2 just worx! THX
Could U help me with logout?
What should be the correct lines to logout in my test.py?

**Comment by h00t2y** [comment]
Nevermind. It was some typo.

async def main() -> None:
    async with SagemcomClient(HOST, USERNAME, PASSWORD, ENCRYPTION_METHOD) as client:
        try:
            await client.login()
        except Exception as exception:  
            print(exception)
            return

        devices = await client.get_hosts()

        for device in devices:
            if device.active:
                print(f"{device.id} - {device.name}")

        await client.logout()

asyncio.run(main())

Now it worx! thx
