### ISSUE TITLE
F@st 5866T

### ISSUE THREAD

**Issue by MiG-41** [iMicknl/python-sagemcom-api#346]
## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               |   F@st 5866T    |
| Hardware Version         |   1,0    |
| Software Version         |    SGJy100058   |

## Describe the bug

After executing code (no matter if sha256 or md5) answer is like this:

![image](https://github.com/user-attachments/assets/97771aed-2086-4f05-b5ec-87fac5a4ad49)

Also in debug page $.xmo. functions gives not expected values:
![image](https://zapodaj.net/images/fd678d10ee5ec.png)

## To Reproduce

run the script

[bug]

**Comment by iMicknl** [comment]
Which version of the script do you run? Unfortunately this means that your router is not supported because it doesn't have the API. If you use the latest version, you should receive an "UnsupportedHostException".
