### ISSUE TITLE
Automatically determine the EncryptionMethod

### ISSUE THREAD

**Issue by iMicknl** [iMicknl/python-sagemcom-api#35]

**Comment by iMicknl** [comment]
A bit of context, you will receive a  (HTTP) TimeOut when the wrong encryption method is selected. However, you will receive this TimeOut as well when you try communication of http(s), when this is not supported...

**Comment by barnouch** [comment]
I can't access to the xpath
![358902939_498517329139114_3377358483880616649_n](https://github.com/iMicknl/python-sagemcom-api/assets/4481234/d6c402e2-217e-4493-9e77-dc3d13e9a053)
