### ISSUE TITLE
Sagemcom F3896LG-ZG not supported

### ISSUE THREAD

**Issue by mgyucht** [iMicknl/python-sagemcom-api#361]
## Model information

| Key                      | Value |
| ------------------------ | ----- |
| Model name               |  Sagemcom F3896LG-ZG     |
| Hardware Version         |  1.2     |
| Software Version         |   LG-RDK_8.10.26-2309.3    |

## Describe the bug

My router model doesn't seem to support this library. It is a Sagemcom F3896LG-ZG, provided by Ziggo for internet in the Netherlands. 

When I tried to use your library, requests to the /cgi/json-req endpoint just responded with a 404 and a webpage. Will update this issue with the exact code I used & error response when I have a minute later today or tomorrow.

I ended up building a separate version: https://github.com/mgyucht/sagemcom-f3896lg-zg-api. Let me know if you think this makes sense to incorporate somehow into your library. Its architecture/structure seems quite different compared to yours. Maybe I'm missing something...

## Expected behavior

Give a clear and concise description of what you expected to happen.

## Screenshots
<img width="801" alt="Screenshot 2024-10-18 at 18 11 10" src="https://github.com/user-attachments/assets/8d0dd5e9-41f9-4cb8-b437-7484296c5ea2">

## Additional context

[bug]

**Comment by iMicknl** [comment]
The Ziggo router uses a different firmware without this endpoint most likely :(. Since these endpoints are very different, I am not sure if it makes sense to merge these efforts. Perhaps best to keep then apart as different Python packages.

Nice work though!

**Comment by mgyucht** [comment]
Thanks for confirming and for taking a look!.

I'll make a PR to update the readme with this information, if that's alright with you.

**Comment by FransHalsjes** [comment]
That is Great! How can I include this library to interact with Home Assistant?
