### ISSUE TITLE
Support for FAST4353-A

### ISSUE THREAD

**Issue by nick8888** [iMicknl/python-sagemcom-api#4]
I couldn't find developer tools etc but here are some of the device details.

FAST4353-A
SG7M100000184
1.57.59.3
A2pv6F039x6.d26r

Please let me know if you are able to support this version or if you require any further details.

**Comment by iMicknl** [comment]
Thanks for reporting. I just saw your email and will have a look this week.

What is your use-case? Is it Home Assistant or another use-case?

**Comment by nick8888** [comment]
Thanks Mick,

Use case is Home Assistant.

Not sure if this helps but $.xmo.logIn("admin", "password"); gives the following error:

Logging error: "Undefined (Access denied via this network interface)" (16777226)

Same as the comment here: https://whrl.pl/Rfnv4b

I have also managed to get root SSH access by following steps here: https://whrl.pl/RgapjB

**Comment by iMicknl** [comment]
@nick8888 looking at your email, it should already work with this package. Could you try using `local_admin` as the username? I am not sure if you need to add a password, that wasn't clear from your email.

**Comment by iMicknl** [comment]
@nick8888 were you able to solve this? I will have a better look at this package in the coming weeks.

**Comment by nick8888** [comment]
Hi Mick,

No unfortunately. Username: Iocal_admin and correct password didn't work unfortunately. The request in your code appeared to match that of the router as you said. However, I tried to troubleshoot but couldn't find much detail in the logs.

**Comment by iMicknl** [comment]
@nick8888 are you able to use the Python package directly for testing? Otherwise, I will need to see if I can update the Home Assistant version...

I am working on a new version in https://github.com/iMicknl/python-sagemcom-api/tree/v1.0.0.

**Comment by pepedocs** [comment]
Thanks for sharing this. My use case is for home assistant and I'm getting the same error. I also printed out the response (below).

```
{'reply': {'uid': 0, 'id': 0, 'error': {'code': 16777216, 'description': 'Ok'}, 'actions': [{'uid': 1, 'id': 0, 'error': {'code': 16777238, 'description': 'Applied'}, 'callbacks': [{'uid': 1, 'result': {'code': 16777238, 'description': 'Applied'}, 'xpath': 'Device', 'parameters': {'id': 1048374586, 'nonce': '1882715252'}}]}], 'events': []}}
```

I hope this helps.
